const mongoose=require("mongoose");
const CourseDeatilsSchema= new mongoose.Schema({
    bannerSection:{
        courseName:String,
        backgroundImageUrl:String,
        imageUrl:String,
        title:String,
        subTitle:String,
        courseFee:Number,
        duration:String,
        startDate:String,
        trainingMode:String,
    },
    sectionOne:[
        {
            imageUrl:String,
            title:String
        }
    ],
    sectionTwo:{
        title:String,
        description1:String,
        description2:String
    },
    curriculum:[
        {
            title:String,
            points:[
                {
                    description:String
                }
            ]
        }
    ],
    onlineTraining:{
        description1:String,
        description2:String
    },
    SelfplaceTraining:{
        description1:String,
        description2:String
    },
    classroomTraining:{
        description1:String,
        description2:String
    },
    CorporateTraining:{
        description1:String,
        description2:String
    },
    advantagesSection:{
        title:String,
        advantages:[
            {
                description:String
            }
        ]
    },
    toolsSection:{
        title:String,
        tools:[
            {
                imageUrl:String,
                description:String
            }
        ]
    },
    videoSection:{
        videoUrl:String
    },
    enrollSection:{
        title:String,
        description:String,
        points:[
            {
                imageeUrl:String,
                description:String
            }
        ]
    },
    oppurtunitiesSection:{
        title:String,
        jobs:[
            {
                jobTitle:String
            }
        ]
    },
    highLightsSection:{
        title:String,
        highlights:[
            {
                description:String
            }
        ]
    }

})
module.exports=new mongoose.model("CourseDetail",CourseDeatilsSchema);